image:
  file: .gitpod.Dockerfile

tasks:
  - command: |
        pwsh -command '../../PSU/Universal.Server'

ports:
  - port: 5000
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - ms-vscode.powershell-preview
    - ms-azuretools.vscode-docker
    - muhammad-sammy.csharp
    - adpyke.codesnap
    - formulahendry.auto-close-tag
