image: gitpod/workspace-full

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-vscode.powershell-preview

tasks:
  - command: sudo docker-up
    name: Docker daemon
  - command: docker
    name: build docker image
  - command: docker build --pull --rm -f ".gitpod.Dockerfile" -t universalgitpod:latest "." && docker run --rm -d  -p 5000:5000/tcp universalgitpod:latest

ports:
  - port: 5000
    visibility: public
    onOpen: open-browser
