image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-vscode.powershell-preview


tasks:
  - init: pwsh
    command: pwsh -command docker run --rm -d  -p 5000:5000/tcp universalgitpod:latest

ports:
  - port: 5000
    visibility: public
    onOpen: open-browser
